"""
Generate a human-readable markdown conformance report from tck-results.json.

Usage:
    python -m tests.tck.report \
        --results build/tck-baseline-results.json \
        --out     docs/tck/baseline-YYYY-MM-DD.md \
        --baseline-out tests/tck/baseline.json
"""

from __future__ import annotations

import argparse
import collections
import json
import sys
from datetime import date
from pathlib import Path


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="tests.tck.report")
    p.add_argument("--results", required=True, type=Path)
    p.add_argument("--out", required=True, type=Path)
    p.add_argument("--baseline-out", type=Path, default=None,
                   help="Write machine-readable pass count for CI gating")
    p.add_argument("--title", default=None)
    args = p.parse_args(argv)

    data = json.loads(args.results.read_text())
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(_render(data, args.title or f"openCypher TCK Baseline ({date.today().isoformat()})"))

    if args.baseline_out is not None:
        backend = data[0]["backend"] if data else "extension"
        args.baseline_out.parent.mkdir(parents=True, exist_ok=True)
        args.baseline_out.write_text(json.dumps({
            "backend": backend,
            "total": len(data),
            "pass": sum(1 for r in data if r["status"] == "pass"),
            "fail": sum(1 for r in data if r["status"] == "fail"),
            "error": sum(1 for r in data if r["status"] == "error"),
            "skipped": sum(1 for r in data if r["status"] == "skipped"),
            "generated_from": str(args.results),
        }, indent=2))
    return 0


def _render(data: list[dict], title: str) -> str:
    total = len(data)
    counts = collections.Counter(r["status"] for r in data)
    pct = {k: 100 * counts[k] / total for k in counts}

    by_dir: dict[str, collections.Counter] = {}
    by_file: dict[str, collections.Counter] = {}
    error_classes: collections.Counter = collections.Counter()
    crashes: list[dict] = []

    for r in data:
        top = r["feature_file"].split("/")[0]
        by_dir.setdefault(top, collections.Counter())[r["status"]] += 1
        by_file.setdefault(r["feature_file"], collections.Counter())[r["status"]] += 1
        if r["status"] == "error":
            diag = (r.get("diagnostic") or "")
            if "ExtensionCrash" in diag or "exited unexpectedly" in diag or "extension worker" in diag:
                error_classes["ExtensionCrash"] += 1
                crashes.append(r)
            elif ":" in diag:
                error_classes[diag.split(":", 1)[0]] += 1
            else:
                error_classes["Other"] += 1

    out: list[str] = []
    out.append(f"# {title}")
    out.append("")
    out.append("Generated by `python -m tests.tck.report` from "
               "`build/tck-baseline-results.json`. **Do not edit by hand** — "
               "regenerate after every run.")
    out.append("")

    # Headline
    out.append("## Headline")
    out.append("")
    out.append(f"- **Total scenarios:** {total}")
    out.append(f"- **Pass:** {counts['pass']}  ({pct.get('pass', 0):.1f}%)")
    out.append(f"- **Fail:** {counts['fail']}  ({pct.get('fail', 0):.1f}%)")
    out.append(f"- **Error:** {counts['error']}  ({pct.get('error', 0):.1f}%)")
    out.append(f"- **Skipped:** {counts['skipped']}  ({pct.get('skipped', 0):.1f}%)")
    out.append("")

    # Error breakdown
    if error_classes:
        out.append("### Error breakdown")
        out.append("")
        out.append("| Class | Count |")
        out.append("|---|---:|")
        for k, n in error_classes.most_common():
            out.append(f"| {k} | {n} |")
        out.append("")

    # Crash list
    if crashes:
        out.append("### Extension crashes (P0)")
        out.append("")
        out.append(f"{len(crashes)} scenario(s) caused the extension worker subprocess to die "
                   "(typically SIGSEGV). These are not soft errors — the C extension hit a bad "
                   "address. Each one is a P0 bug.")
        out.append("")
        out.append("| Feature file | Scenario |")
        out.append("|---|---|")
        for r in crashes:
            out.append(f"| `{r['feature_file']}` | {r['scenario_name']} |")
        out.append("")

    # By top-level dir
    out.append("## Breakdown by top-level area")
    out.append("")
    out.append("| Area | Total | Pass | Fail | Error | Skipped | Pass % |")
    out.append("|---|---:|---:|---:|---:|---:|---:|")
    for top in sorted(by_dir):
        c = by_dir[top]
        tot = sum(c.values())
        out.append(f"| {top} | {tot} | {c['pass']} | {c['fail']} | {c['error']} "
                   f"| {c['skipped']} | {100 * c['pass'] / tot:.1f}% |")
    out.append("")

    # Top failing files
    out.append("## Top 20 most-failing feature files")
    out.append("")
    out.append("Ranked by `fail + error` count. Click through to the vendored TCK file "
               "under `vendor/tck/features/<path>`.")
    out.append("")
    out.append("| Failures | Feature file |")
    out.append("|---:|---|")
    ranked = sorted(
        ((f, c) for f, c in by_file.items()),
        key=lambda kv: kv[1]["fail"] + kv[1]["error"],
        reverse=True,
    )
    for f, c in ranked[:20]:
        out.append(f"| {c['fail'] + c['error']} | `vendor/tck/features/{f}` |")
    out.append("")

    out.append("## Notes")
    out.append("")
    out.append("- `skipped` scenarios are not failures — they're cases the harness's "
               "Gherkin step vocabulary or value parser doesn't yet decode. Closing the "
               "skip rate is a harness improvement task, not a parser/executor task.")
    out.append("- `fail` means the query parsed and ran but produced a different result than "
               "the TCK expected. Triage in [[GQLITE-T-0211]] decides bug vs. feature-request.")
    out.append("- `error` means the extension raised — either a clean SQLite error or, in 8 "
               "cases, a subprocess crash. Crashes are listed above and become P0 backlog "
               "items in [[GQLITE-T-0211]].")
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    raise SystemExit(main())
